web:
  upload-path: ${app.upload.ueditor} #此处最后需带上/否则无法识别
  qr-code-path: ${app.upload.QRCode} #此处最后需带上/否则无法识别
  profile: ${app.upload.profile} #此处最后需带上/否则无法识别
server:
  port: ${app.port} #程序访问端口号
  servlet:
    context-path: ${app.contentpath} #程序访问上下文路径
spring:
  resources:
    static-locations: file:${web.upload-path},file:${web.qr-code-path},file:${web.profile},classpath:/static/,classpath:/templates/
  mvc:
    static-path-pattern: /**
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
config:
  ueditor:
    serverPath: ${app.serverPath} #此处最后需带上/否则无法识别
    web-qr-code-path: ${app.qrcodepath} #二维码地址
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
database:
  driver: ${app.driverClassName}
  url: ${app.jdbcUrl}
  username: ${app.username}
  password: ${app.password}

