web:
  upload-path: /Users/jaydenwu/Documents/Home/upload/ueditor/ #此处最后需带上/否则无法识别
  qr-code-path: /Users/jaydenwu/Documents/Home/upload/QRCode/ #此处最后需带上/否则无法识别
  profile: /Users/jaydenwu/Documents/Home/upload/profile/ #此处最后需带上/否则无法识别
server:
  port: 8999 #程序访问端口号
  servlet:
    context-path: /assistant #程序访问上下文路径
spring:
  resources:
    static-locations: file:${web.upload-path},file:${web.qr-code-path},file:${web.profile},classpath:/static/,classpath:/templates/
  mvc:
    static-path-pattern: /**
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html
config:
  ueditor:
    serverPath: http://192.168.1.102:8999/assistant/ #此处最后需带上/否则无法识别
    web-qr-code-path: http://192.168.1.102:8999/assistant/member/info?memberId= #二维码地址
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
